name: Python application

on:
  push:
    branches: [ "main", "backed" ]
  pull_request:
    branches: [ "main", "backed" ]


permissions:
  contents: read

jobs:
  build:

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Display Python version and environment
      run: |
        python --version
        pip --version
        pip list

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
