name: CI

on:
  push:
    branches: [ "main", "backend" ]
  pull_request:
    branches: [ "main", "backend" ]

permissions:
  contents: read

env:
  PYTHON_VERSION: "3.10"
  NODE_VERSION: "16"
  FRONTEND_DIR: "./iptv/iptv-react"
  FRONTEND_BUILD_DIR: "./iptv/iptv-react/build/"
  FRONTEND_PACKAGE_LOCK: "./iptv/iptv-react/package-lock.json"

jobs:
  backend:
    name: Backend - Python
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Cache Python packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: Run Tests
        run: |
          pip install pytest
          pytest

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: ./test-results/

      - name: Build Application
        run: |
          echo "Backend build step - customize as needed"

  frontend:
    name: Frontend - React
    runs-on: ubuntu-latest
    needs: backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles(env.FRONTEND_PACKAGE_LOCK) }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Node.js dependencies
        run: npm install
        working-directory: ${{ env.FRONTEND_DIR }}

      - name: Lint frontend code
        run: npm run lint
        working-directory: ${{ env.FRONTEND_DIR }}

      - name: Run frontend tests
        run: npm test -- --coverage
        working-directory: ${{ env.FRONTEND_DIR }}

      - name: Build frontend
        run: npm run build
        working-directory: ${{ env.FRONTEND_DIR }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: frontend-build
          path: ${{ env.FRONTEND_BUILD_DIR }}
